# Generated by Django 6.0.7 on 2026-07-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Дата оплаты"),
        ),
    ]
