# Generated by Django 6.0.7 on 2026-07-29 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_managers_remove_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="payment",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="method",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="paid_lesson",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_date",
        ),
        migrations.AddField(
            model_name="payment",
            name="amount_cents",
            field=models.PositiveIntegerField(default=0, verbose_name="Сумма в копейках"),
        ),
        migrations.AddField(
            model_name="payment",
            name="amount_rub",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Сумма в рублях"),
        ),
        migrations.AddField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(default="", verbose_name="Ссылка на оплату"),
        ),
    ]
