# Generated by Django 6.0.7 on 2026-07-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_options_remove_payment_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
