# Generated by Django 6.0.7 on 2026-07-28 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribed_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписчики",
            ),
        ),
    ]
