# Generated by Django 6.0.7 on 2026-07-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_course_subscribers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="subscribers",
        ),
    ]
