# Generated by Django 6.0.7 on 2026-07-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_remove_course_subscribers"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                help_text="Заполняется автоматически при создании цены",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="ID продукта в Stripe",
            ),
        ),
    ]
