# Generated by Django 6.0.7 on 2026-07-28 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_course_subscribers"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="subscribed_at",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions_from_subscription_model",
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
    ]
