# Generated by Django 6.0.7 on 2026-07-28 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_course_subscribers"),
        (
            "subscriptions",
            "0002_rename_subscribed_at_subscription_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
    ]
